### ISSUE TITLE
Creating `Atom`s

### ISSUE THREAD

**Issue by peacememories** [potassco/clingo-rs#12]
We're using the rust clingo bindings to generate grounded programs that we would then like to solve with a few facts added as assumptions. the `assumptions` argument of `Control::solve` seems like the way to go, but I can't find any way to generate a `Literal` or `Atom`, from a `Symbol` or otherwise. I would greatly appreciate any advice :)

**Comment by sthiele** [comment]
I think the best way would be to use the [ProgramBuilder](https://docs.rs/clingo/0.6.0/clingo/ast/struct.ProgramBuilder.html)  for that. 
```
...
    let mut ctl = Control::new(options).expect("Failed creating Control.");
    let mut builder = ast::ProgramBuilder::from(self.control).unwrap();

    let sym = Symbol::create_id("test", true).unwrap();
    let term = Term::from(sym);
    let lit = ast::Literal::from_term(Sign::None, &term);
    let hlit = HeadLiteral::from(&lit);
    let rule = Rule::new(hlit, &[]);
    let stmt = rule.ast_statement();

    // add the rewritten statement to the program
    builder
        .add(&stmt)
        .expect("Failed to add statement to ProgramBuilder.");
```

Also see the [ast example](https://github.com/potassco/clingo-rs/blob/master/examples/ast.rs).

**Comment by peacememories** [comment]
I'm guessing i'd need to ground the program again afterwards? Sorry for these naive questions, I'm not really familiar with clingo yet^^'

**Comment by sthiele** [comment]
Yes `ProgramBuilder` is used before grounding. After grounding you could get the [`SymbolicAtoms`](https://docs.rs/clingo/0.6.0/clingo/struct.Control.html#method.symbolic_atoms) and then use the method [`literal()`](https://docs.rs/clingo/0.6.0/clingo/struct.SymbolicAtom.html#method.literal).

Also see the [symbolic atoms example](https://github.com/potassco/clingo-rs/blob/master/examples/symbolic-atoms.rs).

**Comment by peacememories** [comment]
Thanks for clearing up my confusion :) I’m going to close this, since it’s not an issue with the library :)
