### ISSUE TITLE
Remove 3.0.1 release tag?

### ISSUE THREAD

**Issue by pluehne** [potassco/clingo-rs#22]
I stumbled upon the [`v3.0.1` tag](https://github.com/potassco/clingo-rs/releases/tag/v3.0.1), which appears to be made in error. The tag is for a commit made almost two years ago and behind the `master` branch by more than 100 commits. The latest release, `v0.6.0`, is more recent despite its lower version number.

I’d suggest removing the `v3.0.1` tag. It’s not been published on crates.io as far as I can tell, so the risk of others depending on the `v3.0.1` is low. However, I think that the tag is still problematic because it takes precedence over actually newer tags (such as `v0.6.0`) according to semantic versioning.

**Comment by sthiele** [comment]
Thank you. I removed the tag.

**Comment by pluehne** [comment]
@sthiele: Thanks!
