### ISSUE TITLE
Assign external variables

### ISSUE THREAD

**Issue by power-fungus** [potassco/clingo-rs#27]
I would like to use clingo in Multi-shot mode. This seems possible via the use of external atoms and [`assign_external`](https://docs.rs/clingo/0.6.0/clingo/struct.Control.html?search=#method.assign_external). However, how do I get the literal or atom for the correct external symbol?

Idea:

asp file contains `#external p(1;2;3).`
rust program: `control.assign_external(<description of "p(1)">, TruthValue::True);`

**Comment by sthiele** [comment]
After grounding you can get the [`SymbolicAtoms`](https://docs.rs/clingo/0.6.0/clingo/struct.Control.html#method.symbolic_atoms) and then use the method [`literal()`](https://docs.rs/clingo/0.6.0/clingo/struct.SymbolicAtom.html#method.literal).

Also see the [symbolic atoms example](https://github.com/potassco/clingo-rs/blob/master/examples/symbolic-atoms.rs).

**Comment by power-fungus** [comment]
thank you, my bad
