### ISSUE TITLE
Add new rule that does not introduce new Atoms

### ISSUE THREAD

**Issue by drwadu** [potassco/clingo-rs#43]
I am trying to avoid grounding, while adding new rules to the underlying logic program, which means [adding](https://docs.rs/clingo/0.6.0/clingo/struct.Control.html#method.add) a new program that extends the old program by the new rules is not an option. 

I was planning to use [`rule`](https://docs.rs/clingo/0.6.0/clingo/struct.Backend.html#method.rule), which accepts `&[Atom]` for the `head`-parameter. Among the [examples](https://github.com/potassco/clingo-rs/tree/master/examples) I could only find cases where the head of the added rule
is either empty, or introducing new atoms. 

  1. How do I add rules that **do not** introduce new atoms in the head?
  2. Is there a way to convert a [`Symbol`](https://docs.rs/clingo/0.6.0/clingo/struct.Symbol.html) or a [`Literal`](https://docs.rs/clingo/0.6.0/clingo/struct.Literal.html) to an [`Atom`](https://docs.rs/clingo/0.6.0/clingo/struct.Atom.html)?

I might just fail to see it.

**Comment by sthiele** [comment]
Thanks for pointing that out. It is missing in the API. 
In branch [backport-0.6/issue43](https://github.com/potassco/clingo-rs/tree/backport-0.6/issue43) I added an `impl From<Literal> for Atom`.
You may want to use that branch because the next release will include some breaking changes.
