### ISSUE TITLE
Solve with mut ref to Control object

### ISSUE THREAD

**Issue by drwadu** [potassco/clingo-rs#58]
As far as I can tell versions <0.7 used a `SolveHandle` object based on a mutable reference to `clingo_solve-handle_t`. 
https://github.com/potassco/clingo-rs/blob/44b95d91763ce500ba6901cfa7c8d5ffabc1d08c/src/lib.rs#L4761

As opposed to 
https://github.com/potassco/clingo-rs/blob/26d3114ee6a66aed29d9dbbf8503ad31f72ffa69/src/lib.rs#L4974
`SolveHandle` does not move the underlying `Control` object. This is in particular useful, as one's not forced to construct a new `Control` object whenever enumerating answer sets by means of `solve` or `all_models`. 

This is why I propose to add the old `SolveHandle` implementation.

**Comment by sthiele** [comment]
Thank you @drwadu 
The old  behavior  was unsafe as it generated two mutable references to the underlying control object.
The first  is in the original `Control` object and a second through the `SolveHandle`.
That is why `solve` is now consuming the control object and calling `close` on the `SolveHandle` returns you the `Control` object.
I don't want to reintroduce the unsafe behavior but I would be interested to know more about how this causes problems for you and maybe we can find another solution.

**Comment by drwadu** [comment]
thx @sthiele for your reponse.

I see your point, and understand your preference to not reintroduce the unsafe behavior. 

Let me give a minimal example, and briefly explain what's required in my use case:
I want  to ground exactly once, and then interactively compute answer sets, brave, and cautious consequences with designated assumptions. So, essentially, I use the `Control` object (1) to ground once; and (2) to generate multiple solve handles, one at a time. Based on https://github.com/drwadu/clingo-rs/tree/solve-handle-issue,  for instance, I do the following:
```rust
    pub fn enumerate_solutions<S: ToString>(
        &mut self,
        upper_bound: Option<usize>,
        assumptions: &[clingo::SolverLiteral],
    ) -> Result<usize> {
        let mut handle = self.ctl.solve_mut_ref(clingo::SolveMode::YIELD, assumptions)?;
        let mut i = 0;

        match upper_bound {
            None => {
                while let Ok(Some(answer_set)) = handle.model() {
                    println!("solution {:?}: ", i + 1);
                    let atoms = answer_set.symbols(clingo::ShowType::SHOWN)?;
                    atoms.iter().for_each(|atom| {
                        print!("{} ", atom.to_string());
                    });
                    println!();

                    i += 1;
                    handle.resume()?;
                }
            }
            Some(n) => {
                while let Ok(Some(answer_set)) = handle.model() {
                    println!("solution {:?}: ", i + 1);
                    let atoms = answer_set.symbols(clingo::ShowType::SHOWN)?;
                    atoms.iter().for_each(|atom| {
                        print!("{} ", atom.to_string());
                    });
                    println!();

                    i += 1;
                    if i == n {
                        break;
                    }
                    handle.resume()?;
                }
            }
        }

        handle
            .close()
            .map_err(|e| errors::SomeError::Clingo(e))?;

        return Ok(i);
    }
```
 I don't think that the unsafe behavior causes problems for my use case. I might, however, overlook something.

thx for your help

**Comment by sthiele** [comment]
Would rewriting it like this help?
```
pub fn enumerate_solutions<C:ControlCtx,S: ToString>(
    ctl: GenericControl<C>,
    upper_bound: Option<usize>,
    assumptions: &[clingo::SolverLiteral],
) -> Result<(GenericControl<C>,usize), ClingoError> {
    let mut handle = ctl.solve(clingo::SolveMode::YIELD, assumptions)?;
    let mut i = 0;

    match upper_bound {
        None => {
            while let Ok(Some(answer_set)) = handle.model() {
                println!("solution {:?}: ", i + 1);
                let atoms = answer_set.symbols(clingo::ShowType::SHOWN)?;
                atoms.iter().for_each(|atom| {
                    print!("{} ", atom.to_string());
                });
                println!();

                i += 1;
                handle.resume()?;
            }
        }
        Some(n) => {
            while let Ok(Some(answer_set)) = handle.model() {
                println!("solution {:?}: ", i + 1);
                let atoms = answer_set.symbols(clingo::ShowType::SHOWN)?;
                atoms.iter().for_each(|atom| {
                    print!("{} ", atom.to_string());
                });
                println!();

                i += 1;
                if i == n {
                    break;
                }
                handle.resume()?;
            }
        }
    }

    let retctl=handle
        .close()?;

    return Ok((retctl,i));
}
```

**Comment by drwadu** [comment]
unfortunately, no. FYI: I used `self.ctl` with `&mut self`. 

it says **"move occurs because self.ctl has type GenericControl<Non, Non, Non, Non>, which does not implement the copy trait"**

The particular parts where I require the functionality can be found in
- https://github.com/drwadu/savan/blob/3a4fd091a3d9dc23561e747bad5533a5dfb0dda3/src/nav/mod.rs#L43C5-L43C5;
- https://github.com/drwadu/savan/blob/3a4fd091a3d9dc23561e747bad5533a5dfb0dda3/src/nav/mod.rs#L100;
- https://github.com/drwadu/savan/blob/3a4fd091a3d9dc23561e747bad5533a5dfb0dda3/src/nav/facets.rs#L6.

**Comment by sthiele** [comment]
I opened a PR https://github.com/drwadu/savan/pull/1/commits/b00e0d060cf5922b4422e355129a665cd6cfeb3c
